import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MoneyConverterDrawer from './components/MoneyConverterDrawer';
import { Footer, Navbar } from "./components/navbar/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// app/layout.tsx
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  // optional, but helps prevent odd auto-zoom:
  maximumScale: 1,
  userScalable: false,
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <MoneyConverterDrawer  />
        <Footer/>
      </body>
    </html>
  );
}
